version: "3.9"
services:
  projector:
    build: .
    ports:
      - "8887:8887"
    volumes:
      - ~/projector-docker:/home/projector-user:cached
      - ~/workspace:/home/projector-user/workspace:cached